### PR TITLE
Replace shell script with snakemake

### PR DESCRIPTION
**Pull request by cookkate**
- [ ] add temposeq steps
- [ ] double check that RNA-seq is identical

### CODE REVIEW

**Comment by cookkate** [comment]
wait I wasn't done!

**Comment by mattjmeier** [comment]
Oh. Whoops!

I don't think I can reverse it, can I. What would you like me to do? I can probably go back in time on the command line?

**Comment by cookkate** [comment]
It's ok, I double checked and I didn't do anything that breaks master (this commit was just adding things) so I will start a new branch.

I usually use the pull requests for in progress things to keep collaborators abreast of what's going on so I opened it pretty early.

**Comment by mattjmeier** [comment]
Ok! I see - next time I will wait, lol.

**Pull request merged**
